"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import cddeploymentinfo as shared_cddeploymentinfo
from ..shared import cddeploymentresource as shared_cddeploymentresource
from dataclasses_json import Undefined, dataclass_json
from pan import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class CdPipelineResourceResult:
    r"""CD resource results"""
    deployment_info: Optional[shared_cddeploymentinfo.CDDeploymentInfo] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('deploymentInfo'), 'exclude': lambda f: f is None }})
    resources: Optional[list[shared_cddeploymentresource.CDDeploymentResource]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('resources'), 'exclude': lambda f: f is None }})
    

