"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import connectionsrulerecommendation as shared_connectionsrulerecommendation
from ..shared import recommendationtimeperiod as shared_recommendationtimeperiod
from dataclasses_json import Undefined, dataclass_json
from pan import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ConnectionsRuleRecommendationPeriod:
    connections_rule_recommendations: Optional[list[shared_connectionsrulerecommendation.ConnectionsRuleRecommendation]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('connectionsRuleRecommendations'), 'exclude': lambda f: f is None }})
    time_period: Optional[shared_recommendationtimeperiod.RecommendationTimePeriod] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('timePeriod'), 'exclude': lambda f: f is None }})
    total_connections: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('totalConnections'), 'exclude': lambda f: f is None }})
    

