"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .kubernetesapiruleaction import KubernetesAPIRuleAction
from .kubernetesapiviolationuserrule import KubernetesAPIViolationUserRule
from .matchedrecommendedrule import MatchedRecommendedRule
from dataclasses_json import Undefined, dataclass_json
from pan import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class KubernetesAPIViolation:
    action: Optional[KubernetesAPIRuleAction] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('action'), 'exclude': lambda f: f is None }})
    is_default_rule: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('isDefaultRule'), 'exclude': lambda f: f is None }})
    matched_recommended_rule: Optional[MatchedRecommendedRule] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('matchedRecommendedRule'), 'exclude': lambda f: f is None }})
    r"""recommended rule that might reduce potential risk"""
    user_rule: Optional[KubernetesAPIViolationUserRule] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('userRule'), 'exclude': lambda f: f is None }})
    

