"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OASVersion(str, Enum):
    r"""OpenAPI specification version"""
    OA_SV2_0 = 'OASv2.0'
    OA_SV3_0 = 'OASv3.0'
