"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class RiskSeverity(str, Enum):
    r"""An enumeration."""
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    CRITICAL = 'CRITICAL'
    NEUTRAL = 'NEUTRAL'
    UNKNOWN = 'UNKNOWN'
    NO_RISK = 'NO_RISK'
