"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Role(str, Enum):
    r"""The role of the user"""
    LIGHTSPIN_ADMIN = 'LIGHTSPIN_ADMIN'
    CISCO_SUBSCRIBER = 'CISCO_SUBSCRIBER'
    SELF_PROVISIONING = 'SELF_PROVISIONING'
    CI_CD_SCANNER = 'CI_CD_SCANNER'
    PORTSHIFT_ADMIN = 'PORTSHIFT_ADMIN'
    PORTSHIFT_AUDITOR = 'PORTSHIFT_AUDITOR'
    ACCOUNT_ADMIN = 'ACCOUNT_ADMIN'
    SERVICE = 'SERVICE'
    ACCOUNT_AUDITOR = 'ACCOUNT_AUDITOR'
