"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ServerlessRuleAction(str, Enum):
    r"""serverless rule action"""
    DETECT = 'DETECT'
    ALLOW = 'ALLOW'
    BLOCK = 'BLOCK'
