"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class TestInputDepthEnum(str, Enum):
    r"""An enumeration for input depth parameter."""
    QUICK = 'QUICK'
    DEFAULT = 'DEFAULT'
    DEEP = 'DEEP'
