"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ViolationReason(str, Enum):
    VULNERABILITY = 'VULNERABILITY'
    PSP = 'PSP'
    API = 'API'
    SIDECAR = 'SIDECAR'
