"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class WorkloadType(str, Enum):
    POD = 'POD'
    SYSTEM_POD = 'SYSTEM_POD'
    APP = 'APP'
    EXPANSION = 'EXPANSION'
    EXTERNAL = 'EXTERNAL'
