"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import permissionresponse as shared_permissionresponse
from enum import Enum
from typing import Optional

class GetRiskAssessmentPermissionsClusterIDOwnerIDSortDir(str, Enum):
    r"""sorting direction"""
    ASC = 'ASC'
    DESC = 'DESC'

class GetRiskAssessmentPermissionsClusterIDOwnerIDSortKey(str, Enum):
    r"""sort key"""
    RISK = 'risk'



@dataclasses.dataclass
class GetRiskAssessmentPermissionsClusterIDOwnerIDRequest:
    cluster_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'clusterId', 'style': 'simple', 'explode': False }})
    owner_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'ownerId', 'style': 'simple', 'explode': False }})
    is_approved: Optional[bool] = dataclasses.field(default=False, metadata={'query_param': { 'field_name': 'isApproved', 'style': 'form', 'explode': True }})
    r"""Return approved / not approved entries"""
    sort_dir: Optional[GetRiskAssessmentPermissionsClusterIDOwnerIDSortDir] = dataclasses.field(default=GetRiskAssessmentPermissionsClusterIDOwnerIDSortDir.ASC, metadata={'query_param': { 'field_name': 'sortDir', 'style': 'form', 'explode': True }})
    r"""sorting direction"""
    sort_key: Optional[GetRiskAssessmentPermissionsClusterIDOwnerIDSortKey] = dataclasses.field(default=GetRiskAssessmentPermissionsClusterIDOwnerIDSortKey.RISK, metadata={'query_param': { 'field_name': 'sortKey', 'style': 'form', 'explode': True }})
    r"""sort key"""
    




@dataclasses.dataclass
class GetRiskAssessmentPermissionsClusterIDOwnerIDResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    permission_response: Optional[shared_permissionresponse.PermissionResponse] = dataclasses.field(default=None)
    r"""Success"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

