"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import List, Optional


@dataclasses.dataclass
class GetVulnerabilitiesRequest:
    max_results: Optional[float] = dataclasses.field(default=100, metadata={'query_param': { 'field_name': 'maxResults', 'style': 'form', 'explode': True }})
    r"""The number of entries to return (pagination)"""
    vul_name: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'vulName', 'style': 'form', 'explode': True }})
    r"""vulnerabilities to search for ( as prefix and suffix )"""
    



@dataclasses.dataclass
class GetVulnerabilitiesResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    strings: Optional[List[str]] = dataclasses.field(default=None)
    r"""Success"""
    

