"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import specsandoperationsdiffswidget as shared_specsandoperationsdiffswidget
from enum import Enum
from typing import Optional

class GetDashboardApisecSpecsAndOperationsDiffsQueryParamAPISecSource(str, Enum):
    r"""source filter. an enum representing the source of the APIs service in scope"""
    INTERNAL = 'INTERNAL'
    EXTERNAL = 'EXTERNAL'


@dataclasses.dataclass
class GetDashboardApisecSpecsAndOperationsDiffsRequest:
    api_sec_source: GetDashboardApisecSpecsAndOperationsDiffsQueryParamAPISecSource = dataclasses.field(default=GetDashboardApisecSpecsAndOperationsDiffsQueryParamAPISecSource.INTERNAL, metadata={'query_param': { 'field_name': 'apiSecSource', 'style': 'form', 'explode': True }})
    r"""source filter. an enum representing the source of the APIs service in scope"""
    



@dataclasses.dataclass
class GetDashboardApisecSpecsAndOperationsDiffsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    specs_and_operations_diffs_widget: Optional[shared_specsandoperationsdiffswidget.SpecsAndOperationsDiffsWidget] = dataclasses.field(default=None)
    r"""OK"""
    

