"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import uuidlist as shared_uuidlist
from enum import Enum
from typing import Optional

class QueryParamActionType(str, Enum):
    r"""The ignore action type (ADD/REMOVE)"""
    ADD = 'ADD'
    REMOVE = 'REMOVE'

class SnoozeTime(str, Enum):
    r"""The time to snooze the vulnerability"""
    ALWAYS = 'ALWAYS'
    YEAR = 'YEAR'
    MONTH = 'MONTH'
    WEEK = 'WEEK'


@dataclasses.dataclass
class PostImagesImageIDVulnerabilitiesIgnoreRequest:
    uuid_list: shared_uuidlist.UUIDList = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    action_type: QueryParamActionType = dataclasses.field(metadata={'query_param': { 'field_name': 'actionType', 'style': 'form', 'explode': True }})
    r"""The ignore action type (ADD/REMOVE)"""
    image_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'imageId', 'style': 'simple', 'explode': False }})
    snooze_time: Optional[SnoozeTime] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'snoozeTime', 'style': 'form', 'explode': True }})
    r"""The time to snooze the vulnerability"""
    



@dataclasses.dataclass
class PostImagesImageIDVulnerabilitiesIgnoreResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    

