"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import apireconstructionrequest as shared_apireconstructionrequest
from typing import Optional



@dataclasses.dataclass
class PostAPISecurityOpenAPISpecsCatalogIDReconstructedSpecLearnRequest:
    catalog_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'catalogId', 'style': 'simple', 'explode': False }})
    api_reconstruction_request: Optional[shared_apireconstructionrequest.APIReconstructionRequest] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class PostAPISecurityOpenAPISpecsCatalogIDReconstructedSpecLearnResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

