"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import bfladurationconfiguration as shared_bfladurationconfiguration
from typing import Optional


@dataclasses.dataclass
class PostAPISecurityInternalCatalogCatalogIDBflaLearningRequest:
    bfla_duration_configuration: shared_bfladurationconfiguration.BflaDurationConfiguration = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    catalog_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'catalogId', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class PostAPISecurityInternalCatalogCatalogIDBflaLearningResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    post_api_security_internal_catalog_catalog_id_bfla_learning_201_application_json_uuid_string: Optional[str] = dataclasses.field(default=None)
    r"""Created"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

