"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import poddefinition as shared_poddefinition
from ...models.shared import poddefinition_input as shared_poddefinition_input
from typing import Optional


@dataclasses.dataclass
class PutPodDefinitionsPodIDRequest:
    pod_definition: shared_poddefinition_input.PodDefinitionInput = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    pod_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'podId', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class PutPodDefinitionsPodIDResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    pod_definition: Optional[shared_poddefinition.PodDefinition] = dataclasses.field(default=None)
    r"""Success"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

