"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import podsecuritypolicy as shared_podsecuritypolicy
from typing import Optional


@dataclasses.dataclass
class PutPodSecurityPolicyProfilesProfileIDRequest:
    pod_security_policy: shared_podsecuritypolicy.PodSecurityPolicy = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    profile_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'profileId', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class PutPodSecurityPolicyProfilesProfileIDResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    pod_security_policy: Optional[shared_podsecuritypolicy.PodSecurityPolicy] = dataclasses.field(default=None)
    r"""Success"""
    

